name = "ghostchat-signaling"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "355cd216e930b3561aed915bc7d9d42d"

[[durable_objects.bindings]]
name = "PEER_SESSION"
class_name = "PeerSession"

[[migrations]]
tag = "v3"
new_sqlite_classes = ["PeerSession"]
